### ISSUE TITLE
no configurations works

### ISSUE THREAD

**Issue by glasswork** [Andreone/dokuwiki_inlinetoc#5]
{{INLINETOC}} - this works perfectly.

{{INLINETOC> ns }} - this, and all other configurations, do not work (no output except: inline_ns).

The plugin is installed and enabled.
There are more than 3 headings in the page and in the namespace.
I do not have either the sortablejs plugin or searchtablejs plugin installed.

**Comment by albig** [comment]
I noticed the same.

**Comment by Andreone** [comment]
I don't use Dokuwiki for years, I didnt follow the api changes. Sorry but I can't help you.
